Microsoft, Mozilla, DuckDuckGo, Brave, Vivaldi and nearly every other browser maker (other than Google) did the right thing and said no to FLoC

Browsers supporting FLoC:

Google Chrome

Browsers against FLoC

Microsoft Edge, Internet Explorer, Safari, Opera, Vivaldi, Mozilla Firefox, Brave, DuckDuckGo, Ecosia, and many more

FLoC has already been cracked by DDG, as of APril 12th 2021
