A = "Project language file 1";
B = "For: seanpm2001/Learn-Lucid";
C = "About:";
D = "I decided to make Lucid the main project language file for this project (Seanpm2001/Learn-Lucid) as Lucid is the language this project is dedicated to, because this project is about learning the Lucid programming language. It only makes sense to Lucid the official language for this project. It is getting its own project language file, starting here."

AA = "File info";
AB = "File type: Lucid source file (*.l)";
AC = "File version: 1 (2022, Monday, October 24th at 11:49 pm PST)";
AD = "Line count (including blank lines and compiler line): 10";
