// Start of script

// Notes
// I don't know how to make strings in SourcePawn, so comments will do for now

// Project language file 1
// For: seanpm2001/Learn-SourcePawn
// About:
// I decided to make SourcePawn the main project language file for this project (Seanpm2001/Learn-SourcePawn) as SourcePawn is the language this project is dedicated to, because this project is about learning the SourcePawn programming language. It only makes sense to SourcePawn the official language for this project. It is getting its own project language file, starting here.

// File info
// File type: SourcePawn source file (*.pwn)
// File version: 1 (2022, Sunday, September 4th at 6:48 pm PST)
// Line count (including blank lines and compiler line): 17

// End of script
