WRITE(F"Project language file 1.">);
WRITE(F"For: seanpm2001/Learn-POP-2.">);
WRITE(F"About.">);
WRITE(F"I decided to make POP-2 the main project language file for this project (Seanpm2001/Learn-POP-2) as POP-2 is the language this project is dedicated to, because this project is about learning the POP-2 programming language. It only makes sense to POP-2 the official language for this project. It is getting its own">); project language file, starting here.">);
WRITE(F"***">);
WRITE(F"File info.">);
WRITE(F"File type: POP-2 source file (*.L)">);
WRITE(F"File version: 1 (2024, Wednesday, January 3rd at 09:49 pm PST)">);
WRITE(F"Line count (including blank lines and compiler line): 10">);
