// Start of script

// Notes
// I don't know how to make strings in SourcePawn, so comments will do for now

// Project language file 1
// For: SNU/2D/ProgrammingTools/IDE/SourcePawn
// About:
// I decided to make SourcePawn the main project language file for this project (SNU / 2D / Programming Tools / IDE / SourcePawn) as this is a SourcePawn IDE, and it needs its main language to be represented here.

// File info
// File type: SourcePawn source file (*.inc)
// File version: 1 (2022, Sunday, Sepember 4th at 6:54 pm PST)
// Line count (including blank lines and compiler line): 17

// End of script
