Write("Project language file 1")
Write("For: /SNU/2D/ProgrammingTools/IDE/MQL5")
Write("About:")
Write("I decided to make CPL the main project language file for this project (SNU / 2D / Programming Tools / IDE / CPL) as this is a CPL IDE, and it needs its main language to be represented here.")
Write("==================================")
Write("File info")
Write("File type: CPL (1963) source file (*.alg *.ALG *.c)")
Write("File version: 1 (2023, Monday, December 25th at 11:22 pm PST)")
Write("Line count (including blank lines and compiler line): 10")
