<?xqlint
/* Start of script */

/* Project language file 1
* For: seanpm2001/Learn-EBNF
* About:
* I decided to make EBNF the main project language file for this project (Seanpm2001/Learn-EBNF) as EBNF is the language this project is dedicated to, because this project is about learning the EBNF programming language. It only makes sense to make EBNF the official language for this project. It is getting its own project language file, starting here.
*/

::= 'Project language file 1'
::= 'For: seanpm2001/Learn-EBNF'
::= 'About:'
::= 'I decided to make EBNF the main project language file for this project (Seanpm2001/Learn-EBNF) as EBNF is the language this project is dedicated to, because this project is about learning the EBNF programming language. It only makes sense to make EBNF the official language for this project. It is getting its own project language file, starting here.'

/* File info
* File type: EBNF source file (*.ebnf)
* File version: 1 (2022, Thursday, November 10th at 10:42 pm PST)
* Line count (including blank lines and compiler line): 26
*/

/* End of script */

<?xqlint
});
?>
