; Start of script

#include "macros.inc"

; Project language file 1
; For: /SNU/2D/ProgrammingTools/IDE/UNIX-Assembly/
; About:
; I decided to make UNIX Assembly the main project language file for this project (SNU / 2D / Programming Tools / IDE / UNIX-Assembly) as this is a UNIX Assembly IDE, and it needs its main language to be represented here.

.macro plangone start
    "Project language file 1"
    "For: /SNU/2D/ProgrammingTools/IDE/UNIX-Assembly/"
    "About: "
    "I decided to make UNIX Assembly the main project language file for this project (SNU / 2D / Programming Tools / IDE / UNIX-Assembly) as this is a UNIX Assembly IDE, and it needs its main language to be represented here."
end

; File info
; File type: UNIX Assembly source file (*.S)
; File version: 1 (2022, Friday, November 25th at 11:01 pm PST)
; Line count (including blank lines and compiler line): 23

; End of script
