view layout [text "Note: I don't know how to make comments in REBOL. This message should have been hidden" button "Continue" [quit]]
view layout [text "Project language file 1" button "Continue" [quit]]
view layout [text "For: seanpm2001/Learn-REBOL" button "Quit" [quit]]
view layout [text "About:" button "Quit" [quit]]
view layout [text "I decided to make REBOL the main project language file for this project (Seanpm2001/Learn-REBOL) as REBOL is the language this project is dedicated to, because this project is about learning the REBOL programming language. It only makes sense to REBOL the official language for this project. It is getting its own project language file, starting here." button "Quit" [quit]]
view layout [text "File info:" button "Quit" [quit]]
view layout [text "File type: REBOL source file (*.r *.reb)" button "Quit" [quit]]
view layout [text "File version: 1 (2022, Friday, November 4th at 10:33 pm PST)" button "Quit" [quit]]
view layout [text "Line count (including blank lines and compiler line): 10" button "Quit" [quit]]
