# Project language file 3

## For AquariOS

### About

I chose the API Blueprint language as the 3rd language file for this project (AquariOS) it is being used for hardware blueprints.

### File info

File type: API Blueprint source file (*.apib)
File version: 1 (2022, Monday, March 28th at 1:28 am PST)
Line count (including blank lines and compiler line): 14
