# Python build file
pip require Python-3.6 # It is a bit out of date, but it is what the project uses for versions as of August 14th 2021
# File info
# File version: 1 (Saturday, 2021 August 14th at 6:06 pm)
# File type: Dependency list (open an issue to give a suggestion on how to improve this file)
# Line count (including blank lines and compiler line): 7

