; Start of script

#include "macros.inc"

; Project language file 1
; For: seanpm2001/Learn-UNIX-Assembly
; About:
; I decided to make UNIX Assembly the main project language file for this project (Seanpm2001/Learn-UNIX-Assembly) as UNIX Assembly is the language this project is dedicated to, because this project is about learning the UNIX Assembly programming language. It only makes sense to UNIX Assembly the official language for this project. It is getting its own project language file, starting here.

.macro plangone start
    "Project language file 1"
    "For: seanpm2001/Learn-UNIX-Assembly"
    "About: "
    "I decided to make UNIX Assembly the main project language file for this project (Seanpm2001/Learn-UNIX-Assembly) as UNIX Assembly is the language this project is dedicated to, because this project is about learning the UNIX Assembly programming language. It only makes sense to UNIX Assembly the official language for this project. It is getting its own project language file, starting here."
end

; File info
; File type: UNIX Assembly source file (*.S)
; File version: 1 (2022, Friday, November 25th at 10:55 pm PST)
; Line count (including blank lines and compiler line): 23

; End of script
