Write("Project language file 1")
Write("For: seanpm2001/Learn-CPL")
Write("About:")
Write("I decided to make CPL the main project language file for this project (Seanpm2001/Learn-CPL) as CPL is the language this project is dedicated to, because this project is about learning the CPL programming language. It only makes sense to CPL the official language for this project. It is getting its own project language file, starting here.")
Write("==================================")
Write("File info")
Write("File type: CPL (1963) source file (*.alg *.ALG *.c)")
Write("File version: 1 (2023, Monday, December 25th at 11:28 pm PST)")
Write("Line count (including blank lines and compiler line): 10")
