; START OF SCRIPT

; This script will use up a lot of drum memory.
; Likely not to work anyways in the current state.

PRINT Project language file 1
PRINT For: /SNU/2D/ProgrammingTools/IDE/Speedcode
PRINT About:
PRINT I decided to make Speedcode the main project language file for this
PRINT project (SNU / 2D / Programming Tools / IDE / Speedcode) as this is a
PRINT Speedcode IDE, and it needs its main language to be represented here.

; OUTPUT:

; Project language file 1
; For: /SNU/2D/ProgrammingTools/IDE/Speedcode
; About:
; I decided to make Speedcode the main project language file for this
; project (SNU / 2D / Programming Tools / IDE / Speedcode) as this is a
; Speedcode IDE, and it needs its main language to be represented here.

; FILE INFO

; File type: Speedcode source file (*.S)
; File version: 1 (2024, Monday, January 15th at 10:32 pm PST)
; Line count (including blank lines and compiler line): 29

; END OF SCRIPT
