; START OF SCRIPT

; This script will use up a lot of drum memory.
; Likely not to work anyways in the current state.

PRINT Project language file 1
PRINT For: seanpm2001/Learn-Speedcode
PRINT About:
PRINT I decided to make Speedcode the main project language file for this
PRINT project (Seanpm2001/Learn-Speedcode) as Speedcode is the language 
PRINT this project is dedicated to, because this project is about
PRINT learning the Speedcode programming language. It only makes sense
PRINT to Speedcode the official language for this project. It is
PRINT getting its own, project language file, starting here.

; OUTPUT:

; Project language file 1
; For: seanpm2001/Learn-Speedcode
; About:
; I decided to make Speedcode the main project language file for this
; project (Seanpm2001/Learn-Speedcode) as Speedcode is the language 
; this project is dedicated to, because this project is about
; learning the Speedcode programming language. It only makes sense
; to Speedcode the official language for this project. It is
; getting its own, project language file, starting here.

; FILE INFO

; File type: Speedcode source file (*.S)
; File version: 1 (2024, Monday, January 15th at 10:28 pm PST)
; Line count (including blank lines and compiler line): 35

; END OF SCRIPT
