" Start of script "

" Notes "
" I don't know how to make strings in StringTemplate, so comments will do for now. I also have no reference for StringTemplate, and am thus using SmallTalk syntax. "

" Project language file 1 "
" For: seanpm2001/Learn-StringTemplate "
" About: "
" I decided to make StringTemplate the main project language file for this project (Seanpm2001/Learn-StringTemplate) as StringTemplate is the language this project is dedicated to, because this project is about learning the StringTemplate programming language. It only makes sense to StringTemplate the official language for this project. It is getting its own project language file, starting here. "

" File info "
" File type: StringTemplate source file (*.st) "
" File version: 1 (2022, Thursday, September 22nd at 8:54 pm PST) "
" Line count (including blank lines and compiler line): 17 "

" End of script "
