
## Project language file 1

### For: seanpm2001/API-2001

### About:

I have decided to make API Blueprint the first project language for this project (seanpm2001/API-2001) as I chose this to represent blueprints of the API on this project. It may not be used in a serious context, but it represents the project by name. It is getting its own project language file, starting here.

### File info

File version: 1 (2022, Saturday, May 21st at 3:12 pm PST)

File type: API Blueprint source file (.apib)

Line count (including blank lines and compiler line): 17
