/** Start of script **/

/** Project language file 1
 * For: SNU/2D/ProgrammingTools/IDE/Apex
 * About:
 * I decided to make Apex the main project language file for this project (SNU / 2D / Programming Tools / IDE / Apex) as this is a Apex IDE, and it needs its main language to be represented here.
**/

System.debug('Project language file 1');
System.debug('For: SNU/2D/ProgrammingTools/IDE/Apex');
System.debug('About:');
System.debug('I decided to make Apex the main project language file for this project (SNU / 2D / Programming Tools / IDE / Apex) as this is a Apex IDE, and it needs its main language to be represented here.');

/** File info
 * File type: Apex source file (*.cls)
 * File version: 1 (2022, Saturday, October 8th at 11:37 pm PST)
 * Line count (including blank lines and compiler line): 21
**/

/** End of script **/
