# Project language file 1

## For: SNU/2D/ProgrammingTools/IDE/API-Blueprint

### About

I chose to make API Blueprint the project language for this project (SNU/2D/Programming Tools/IDE/API-Blueprint) as this is a API Blueprint IDE, and API Blueprint should be the official language for the project.

### File info

File type: API Blueprint source file (*.apib)
File version: 1 (2022, Friay, September 16th at 8:32 pm PST)
Line count (including blank lines and compiler line): 14
