/** Start of script **/

/** Project language file 1
 * For: seanpm2001/Learn-Apex
 * About:
 * I decided to make Apex the main project language file for this project (Seanpm2001/Learn-Apex) as Apex is the language this project is dedicated to, because this project is about learning the Apex programming language. It only makes sense to Apex the official language for this project. It is getting its own project language file, starting here.
**/

System.debug('Project language file 1');
System.debug('For: seanpm2001/Learn-Apex');
System.debug('About:');
System.debug('I decided to make Apex the main project language file for this project (Seanpm2001/Learn-Apex) as Apex is the language this project is dedicated to, because this project is about learning the Apex programming language. It only makes sense to Apex the official language for this project. It is getting its own project language file, starting here.');

/** File info
 * File type: Apex source file (*.cls)
 * File version: 1 (2022, Saturday, October 8th at 11:34 pm PST)
 * Line count (including blank lines and compiler line): 21
**/

/** End of script **/
