" Start of script "

" Project language file 1 "
" For: SNU/2D/ProgramingTools/IDE/SmallTalk "
" About: "
" I decided to make SmallTalk the main project language file for this project (SNU / 2D / Programming Tools / IDE / SmallTalk) as this is a SmallTalk IDE, and it needs its main language to be represented here. "

Transcript show: 'Project language file 1'.
Transcript show: 'For: SNU/2D/ProgramingTools/IDE/SmallTalk'.
Transcript show: 'About:'.
Transcript show: 'I decided to make SmallTalk the main project language file for this project (SNU / 2D / Programming Tools / IDE / SmallTalk) as this is a SmallTalk IDE, and it needs its main language to be represented here.'.

" File info "
" File type: SmallTalk source file (*.st) "
" File version: 1 (2022, Thursday, October 6th at 8:09 pm PST) "
" Line count (including blank lines and compiler line): 19 "

" End of script "
