A = "Project language file 1";
B = "For: /SNU/2D/ProgrammingTools/IDE/Lucid/";
C = "About:";
D = "I decided to make Lucid the main project language file for this project (SNU / 2D / Programming Tools / IDE / Lucid) as this is a Lucid IDE, and it needs its main language to be represented here."

AA = "File info";
AB = "File type: Lucid source file (*.l)";
AC = "File version: 1 (2022, Monday, October 24th at 11:55 pm PST)";
AD = "Line count (including blank lines and compiler line): 10";
