# Start of script
# Sample INI file
[.ShellClassInfo]
ConfirmFileOp=0
NoSharing=1
IconFile=GCC.jpeg
IconIndex=0
InfoTip=Some sensible information.
# File info
# File type: Windows INI file [desktop.ini] (*.ini)
# File version: 1 (2021, Thursday, December 16th at 8:33 pm)
# Line count (including blank lines and compiler line): 14
# End of script

