'' Start of script

'' Project language file 1
'' For: /SNU/2D/ProgrammingTools/IDE/PlantUML/
'' About:
'' I decided to make PlantUML the main project language file for this project (SNU / 2D / Programming Tools / IDE / PlantUML) as this is a PlantUML IDE, and it needs its main language to be represented here.

'' File info
'' File type: PlantUML source file (*.puml)
'' File version: 1 (2022, Tuesday, October 18th at 11:52 pm PST)
'' Line count (including blank lines and compiler line): 14

'' End of script
