comment Project language file 1.
comment For: SNU/2D/ProgrammingTools/IDE/POP-1
comment About.
comment I decided to make POP-1 the main project language file for this project (SNU / 2D / Programming Tools / IDE / POP-1) as this is a POP-1 IDE, and it needs its main language to be represented here.
comment ***
comment File info.
comment File type: POP-1 (COWSEL) source file (*.L)
comment File version: 1 (2024, Tuesday, January 2nd at 11:11 pm PST)
comment Line count (including blank lines and compiler line): 10
