view layout [text "Note: I don't know how to make comments in REBOL. This message should have been hidden" button "Continue" [quit]]
view layout [text "Project language file 1" button "Continue" [quit]]
view layout [text "For: /SNU/2D/ProgrammingTools/IDE/REBOL/" button "Quit" [quit]]
view layout [text "About:" button "Quit" [quit]]
view layout [text "I decided to make REBOL the main project language file for this project (SNU / 2D / Programming Tools / IDE / REBOL) as this is a REBOL IDE, and it needs its main language to be represented here." button "Quit" [quit]]
view layout [text "File info:" button "Quit" [quit]]
view layout [text "File type: REBOL source file (*.r *.reb)" button "Quit" [quit]]
view layout [text "File version: 1 (2022, Friday, November 4th at 10:39 pm PST)" button "Quit" [quit]]
view layout [text "Line count (including blank lines and compiler line): 10" button "Quit" [quit]]
