
[variables]
# Start of script

# Notes
# I don't know how to make strings in NASL, so comments will do for now

# Project language file 1
# For: SNU/2D/ProgrammingTools/IDE/NASL
# About:
# I decided to make NASL the main project language file for this project (SNU / 2D / Programming Tools / IDE / NASL) as this is a NASL IDE, and it needs its main language to be represented here.

# File info
# File type: NASL source file (*.inc)
# File version: 1 (2022, Tuesday, October 4th at 10:52 pm PST)
# Line count (including blank lines and compiler line): 19

# End of script
