" Start of script "

" Project language file 1 "
" For: seanpm2001/Learn-SmallTalk "
" About: "
" I decided to make SmallTalk the main project language file for this project (Seanpm2001/Learn-SmallTalk) as SmallTalk is the language this project is dedicated to, because this project is about learning the SmallTalk programming language. It only makes sense to SmallTalk the official language for this project. It is getting its own project language file, starting here. "

Transcript show: 'Project language file 1'.
Transcript show: 'For: seanpm2001/Learn-SmallTalk'.
Transcript show: 'About:'.
Transcript show: 'I decided to make SmallTalk the main project language file for this project (Seanpm2001/Learn-SmallTalk) as SmallTalk is the language this project is dedicated to, because this project is about learning the SmallTalk programming language. It only makes sense to SmallTalk the official language for this project. It is getting its own project language file, starting here.'.

" File info "
" File type: SmallTalk source file (*.st) "
" File version: 1 (2022, Thursday, October 6th at 8:04 pm PST) "
" Line count (including blank lines and compiler line): 19 "

" End of script "
