WRITE(F"Project language file 1.">);
WRITE(F"For: SNU/2D/ProgrammingTools/IDE/POP-2">);
WRITE(F"About.">);
WRITE(F"I decided to make POP-2 the main project language file for this project (SNU / 2D / Programming Tools / IDE / POP-2) as this is a POP-2 IDE, and it needs its main language to be represented here.">);
WRITE(F"***">);
WRITE(F"File info.">);
WRITE(F"File type: POP-2 source file (*.L)">);
WRITE(F"File version: 1 (2024, Wednesday, January 3rd at 09:52 pm PST)">);
WRITE(F"Line count (including blank lines and compiler line): 10">);
