
[variables]
# Start of script

# Notes
# I don't know how to make strings in NASL, so comments will do for now

# Project language file 1
# For: seanpm2001/Learn-NASL
# About:
# I decided to make NASL the main project language file for this project (Seanpm2001/Learn-NASL) as NASL is the language this project is dedicated to, because this project is about learning the NASL programming language. It only makes sense to NASL the official language for this project. It is getting its own project language file, starting here.

# File info
# File type: NASL source file (*.inc)
# File version: 1 (2022, Tuesday, October 4th at 10:49 pm PST)
# Line count (including blank lines and compiler line): 19

# End of script
