%% START OF SCRIPT

%% Project language file 1
%% For: seanpm2001/Learn-Mermaid
%% About:
%% I decided to make Mermaid the main project language file for this project (Seanpm2001/Learn-Mermaid) as Mermaid is the language this project is dedicated to, because this project is about learning the Mermaid programming language. It only makes sense to Mermaid the official language for this project. It is getting its own, project language file, starting here.

sequenceDiagram
loop PLANGONE
    Project language file 1
    For: seanpm2001/Learn-Mermaid
    About:
    I decided to make Mermaid the main project language file for this project (Seanpm2001/Learn-Mermaid) as Mermaid is the language this project is dedicated to, because this project is about learning the Mermaid programming language. It only makes sense to Mermaid the official language for this project. It is getting its own, project language file, starting here.
end

%% FILE INFO

%% File type: Mermaid source file (*.mmd)
%% File version: 1 (2024, Sunday, January 28th at 11:34 pm PST)
%% Line count (including blank lines and compiler line): 15

%% END OF SCRIPT
