comment Project language file 1.
comment For: seanpm2001/Learn-POP-1.
comment About.
comment I decided to make POP-1 the main project language file for this project (Seanpm2001/Learn-POP-1) as POP-1 is the language this project is dedicated to, because this project is about learning the POP-1 programming language. It only makes sense to POP-1 the official language for this project. It is getting its own project language file, starting here.
comment ***
comment File info.
comment File type: POP-1 (COWSEL) source file (*.L)
comment File version: 1 (2024, Tuesday, January 2nd at 11:06 pm PST)
comment Line count (including blank lines and compiler line): 10
