" Start of script "

" Notes "
" I don't know how to make strings in StringTemplate, so comments will do for now. I also have no reference for StringTemplate, and am thus using SmallTalk syntax. "

" Project language file 1 "
" For: SNU/2D/ProgrammingTools/IDE/StringTemplate "
" About: "
" I decided to make StringTemplate the main project language file for this project (SNU / 2D / Programming Tools / IDE / StringTemplate) as this is a StringTemplate IDE, and it needs its main language to be represented here. "

" File info "
" File type: StringTemplate source file (*.st) "
" File version: 1 (2022, Thursday, September 22nd at 8:57 pm PST) "
" Line count (including blank lines and compiler line): 17 "

" End of script "
