HTTP/1.1 200 OK
Date: Tuesday, 2022 November 22nd
Content-Type: text/html; charset=UTF-8
Content-Length: 570
Last-Modified: Tuesday, 2022 November 22nd at 18:45 PST
Server: Apache/2.4.54 (Unix) (Debian/Linux)
ETag:
Accept-Ranges: bytes
Connection: close

<html>
  <head>
    <title>Project language file 1 - Seanpm2001/Learn-HTTP</title>
  </head>
  <body>
    <H1>Project language file 1</H1>
    <H2>For: seanpm2001/Learn-HTTP</H2>
    <H3>About:</H3>
    <p># I decided to make HTTP the main project language file for this project (Seanpm2001/Learn-HTTP) as HTTP is the language this project is dedicated to, because this project is about learning the HTTP language. It only makes sense to make HTTP the official language for this project. It is getting its own project language file, starting here.</p>
  </body>
</html>
